export const GET_EVENTS_REQUEST="GET_EVENTS_REQUEST"
export const GET_EVENTS_SUCCESS="GET_EVENTS_SUCCESS"
export const GET_EVENTS_FAIL="GET_EVENTS_FAIL"
export const GET_EVENTS_RESET="GET_EVENTS_RESET"

export const GET_EVENTS_WITH_LIMIT_REQUEST="GET_EVENTS_WITH_LIMIT_REQUEST"
export const GET_EVENTS_WITH_LIMIT_SUCCESS="GET_EVENTS_WITH_LIMIT_SUCCESS"
export const GET_EVENTS_WITH_LIMIT_FAIL="GET_EVENTS_WITH_LIMIT_FAIL"
export const GET_EVENTS_WITH_LIMIT_RESET="GET_EVENTS_WITH_LIMIT_RESET"

export const GET_EVENTS_MINE_REQUEST="GET_EVENTS_MINE_REQUEST"
export const GET_EVENTS_MINE_SUCCESS="GET_EVENTS_MINE_SUCCESS"
export const GET_EVENTS_MINE_FAIL="GET_EVENTS_MINE_FAIL"
export const GET_EVENTS_MINE_RESET="GET_EVENTS_MINE_RESET"

export const CREATE_EVENT_REQUEST="CREATE_EVENT_REQUEST"
export const CREATE_EVENT_SUCCESS="CREATE_EVENT_SUCCESS"
export const CREATE_EVENT_FAIL="CREATE_EVENT_FAIL"
export const CREATE_EVENT_RESET="CREATE_EVENT_RESET"

export const GET_EVENT_REQUEST="GET_EVENT_REQUEST"
export const GET_EVENT_SUCCESS="GET_EVENT_SUCCESS"
export const GET_EVENT_FAIL="GET_EVENT_FAIL"
export const GET_EVENT_RESET="GET_EVENT_RESET"

export const UPDATE_EVENT_REQUEST="UPDATE_EVENT_REQUEST"
export const UPDATE_EVENT_SUCCESS="UPDATE_EVENT_SUCCESS"
export const UPDATE_EVENT_FAIL="UPDATE_EVENT_FAIL"
export const UPDATE_EVENT_RESET="UPDATE_EVENT_RESET"

export const DELETE_EVENT_REQUEST="DELETE_EVENT_REQUEST"
export const DELETE_EVENT_SUCCESS="DELETE_EVENT_SUCCESS"
export const DELETE_EVENT_FAIL="DELETE_EVENT_FAIL"
export const DELETE_EVENT_RESET="DELETE_EVENT_RESET"
