export const CHANGE_DARK_MODE = "CHANGE_DARK_MODE"
export const LOADING_DATA = "LOADING_DATA"
export const LOADING_RESET = "LOADING_RESET"
export const LIST_BOX__REACT_RAINBOW_SWITCH = "LIST_BOX__REACT_RAINBOW_SWITCH"
