export const POST_IMAGE_REQUEST="POST_IMAGE_REQUEST"
export const POST_IMAGE_SUCCESS="POST_IMAGE_SUCCESS"
export const POST_IMAGE_FAIL="POST_IMAGE_FAIL"
export const POST_IMAGE_RESET="POST_IMAGE_RESET"