export const GET_RENTS_REQUEST="GET_RENTS_REQUEST"
export const GET_RENTS_SUCCESS="GET_RENTS_SUCCESS"
export const GET_RENTS_FAIL="GET_RENTS_FAIL"
export const GET_RENTS_RESET="GET_RENTS_RESET"

export const CREATE_RENT_REQUEST="CREATE_RENT_REQUEST"
export const CREATE_RENT_SUCCESS="CREATE_RENT_SUCCESS"
export const CREATE_RENT_FAIL="CREATE_RENT_FAIL"
export const CREATE_RENT_RESET="CREATE_RENT_RESET"

export const UPDATE_RENT_REQUEST="UPDATE_RENT_REQUEST"
export const UPDATE_RENT_SUCCESS="UPDATE_RENT_SUCCESS"
export const UPDATE_RENT_FAIL="UPDATE_RENT_FAIL"
export const UPDATE_RENT_RESET="UPDATE_RENT_RESET"

