export const GET_STORIES_REQUEST="GET_STORIES_REQUEST"
export const GET_STORIES_SUCCESS="GET_STORIES_SUCCESS"
export const GET_STORIES_FAIL="GET_STORIES_FAIL"
export const GET_STORIES_RESET="GET_STORIES_RESET"

export const GET_STORIES_WITH_LIMIT_REQUEST="GET_STORIES_WITH_LIMIT_REQUEST"
export const GET_STORIES_WITH_LIMIT_SUCCESS="GET_STORIES_WITH_LIMIT_SUCCESS"
export const GET_STORIES_WITH_LIMIT_FAIL="GET_STORIES_WITH_LIMIT_FAIL"
export const GET_STORIES_WITH_LIMIT_RESET="GET_STORIES_WITH_LIMIT_RESET"

export const GET_STORIES_MINE_REQUEST="GET_STORIES_MINE_REQUEST"
export const GET_STORIES_MINE_SUCCESS="GET_STORIES_MINE_SUCCESS"
export const GET_STORIES_MINE_FAIL="GET_STORIES_MINE_FAIL"
export const GET_STORIES_MINE_RESET="GET_STORIES_MINE_RESET"

export const CREATE_STORY_REQUEST="CREATE_STORY_REQUEST"
export const CREATE_STORY_SUCCESS="CREATE_STORY_SUCCESS"
export const CREATE_STORY_FAIL="CREATE_STORY_FAIL"
export const CREATE_STORY_RESET="CREATE_STORY_RESET"

export const GET_STORY_REQUEST="GET_STORY_REQUEST"
export const GET_STORY_SUCCESS="GET_STORY_SUCCESS"
export const GET_STORY_FAIL="GET_STORY_FAIL"
export const GET_STORY_RESET="GET_STORY_RESET"

export const UPDATE_STORY_REQUEST="UPDATE_STORY_REQUEST"
export const UPDATE_STORY_SUCCESS="UPDATE_STORY_SUCCESS"
export const UPDATE_STORY_FAIL="UPDATE_STORY_FAIL"
export const UPDATE_STORY_RESET="UPDATE_STORY_RESET"

export const DELETE_STORY_REQUEST="DELETE_STORY_REQUEST"
export const DELETE_STORY_SUCCESS="DELETE_STORY_SUCCESS"
export const DELETE_STORY_FAIL="DELETE_STORY_FAIL"
export const DELETE_STORY_RESET="DELETE_STORY_RESET"