export const SIGNOUT_USER="SIGNOUT_USER"
export const SIGNOUT_USER_RESET="SIGNOUT_USER_RESET"

export const SIGN_USER_REQUEST="SIGN_USER_REQUEST"
export const SIGN_USER_SUCCESS="SIGN_USER_SUCCESS"
export const SIGN_USER_FAIL="SIGN_USER_FAIL"
export const SIGN_USER_RESET="SIGN_USER_RESET"

export const GOOGLE_SIGN_IN_REQUEST="GOOGLE_SIGN_IN_REQUEST"
export const GOOGLE_SIGN_IN_SUCCESS="GOOGLE_SIGN_IN_SUCCESS"
export const GOOGLE_SIGN_IN_FAIL="GOOGLE_SIGN_IN_FAIL"
export const GOOGLE_SIGN_IN_RESET="GOOGLE_SIGN_IN_RESET"

export const CONFIRM_EMAIL_REQUEST="CONFIRM_EMAIL_REQUEST"
export const CONFIRM_EMAIL_SUCCESS="CONFIRM_EMAIL_SUCCESS"
export const CONFIRM_EMAIL_FAIL="CONFIRM_EMAIL_FAIL"
export const CONFIRM_EMAIL_RESET="CONFIRM_EMAIL_RESET"

export const FORGOT_PASSWORD_REQUEST="FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAIL="FORGOT_PASSWORD_FAIL"
export const FORGOT_PASSWORD_RESET="FORGOT_PASSWORD_RESET"

export const RESET_PASSWORD_REQUEST="RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL="RESET_PASSWORD_FAIL"
export const RESET_PASSWORD_RESET="RESET_PASSWORD_RESET"

export const GET_USER_REQUEST="GET_USER_REQUEST"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_USER_FAIL="GET_USER_FAIL"
export const GET_USER_RESET="GET_USER_RESET"

export const GET_USERS_REQUEST="GET_USERS_REQUEST"
export const GET_USERS_SUCCESS="GET_USERS_SUCCESS"
export const GET_USERS_FAIL="GET_USERS_FAIL"
export const GET_USERS_RESET="GET_USERS_RESET"

export const GET_USER_BY_ID_REQUEST="GET_USER_BY_ID_REQUEST"
export const GET_USER_BY_ID_SUCCESS="GET_USER_BY_ID_SUCCESS"
export const GET_USER_BY_ID_FAIL="GET_USER_BY_ID_FAIL"
export const GET_USER_BY_ID_RESET="GET_USER_BY_ID_RESET"

export const UPDATE_USER_REQUEST="UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL="UPDATE_USER_FAIL"
export const UPDATE_USER_RESET="UPDATE_USER_RESET"

export const DELETE_USER_REQUEST="DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL="DELETE_USER_FAIL"
export const DELETE_USER_RESET="DELETE_USER_RESET"